name: check-resume

on: workflow_dispatch

jobs:
  lint-md-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          npm install -g markdownlint-cli
          markdownlint resume.md